function V_b = Earth_to_body(V_e, roll, pitch, yaw)
    rotx = [1, 0, 0;...
        0, cosd(roll), sind(roll);...
        0, -sind(roll), cosd(roll)];
    roty = [cosd(pitch), 0, -sind(pitch);...
        0, 1, 0;...
        sind(pitch), 0, cosd(pitch)];
    rotz = [cosd(yaw), sind(yaw), 0;...
        -sind(yaw), cosd(yaw), 0;...
        0, 0, 1];
    V_b = rotx * roty * rotz * V_e;
end