function vars = Init(steps, num_targets)

    %accelerations
    a = struct('N', zeros(1,steps), ...
        'E', zeros(1,steps), ...
        'D', zeros(1,steps), ...
        'U', zeros(1,steps));
    
    a.N(1) = 0;
    a.E(1) = 0;
    a.D(1) = 0;
    a.U(1) = 0;
    
    %velocities
    v = struct('N', zeros(1,steps), ...
        'E', zeros(1,steps), ...
        'D', zeros(1,steps), ...
        'U', zeros(1,steps));
    
    v.N(1) = 15;
    v.E(1) = 0;
    v.D(1) = 0;
    v.U(1) = 15;
    
    %positions
    pos = struct('N', zeros(1,steps), ...
        'E', zeros(1,steps), ...
        'D', zeros(1,steps), ...
        'N_desired', zeros(1,steps), ...
        'E_desired', zeros(1,steps))

    pos.N(1) = 0;
    pos.E(1) = 0;
    pos.D(1) = -100;
    
    targets = struct('N', zeros(1,num_targets), ...
        'E', zeros(1,num_targets), ...
        'r', zeros(1,num_targets), ...
        'N_total', zeros(1,max_targets), ...
        'E_total', zeros(1,max_targets), ...
        'r_total', zeros(1,max_targets), ...
        'target_idx', 1);
    
    targets.N(1:3) = [100, 100, 200];
    targets.E(1:3) = [-100, 100, 0];
%     pos.N_targets(1:3) = [100, 200, 100];
%     pos.E_targets(1:3) = [-100, 0, 100];
%     pos.N_targets(1:3) = [200, 100, 100];
%     pos.E_targets(1:3) = [0, -100, 100];

    pos.N_desired(1:3) = pos.N_targets(1);
    pos.E_desired(1:3) = pos.E_targets(1);
    targets.r(1:3) = [5, 10, 5];
    %principal axes (Roll, Pitch, Yaw)
    axes = struct('roll',  zeros(1,steps), ...
        'pitch', zeros(1,steps), ...
        'yaw', zeros(1,steps), ...
        'roll_rate', zeros(1,steps), ...
        'pitch_rate', zeros(1,steps), ...
        'yaw_rate', zeros(1,steps), ...
        'roll_a', zeros(1,steps), ...
        'pitch_a', zeros(1,steps), ...
        'yaw_a', zeros(1,steps), ...
        'roll_desired', zeros(1,steps), ...
        'pitch_desired', zeros(1,steps), ...
        'yaw_desired', zeros(1,steps));
    
    axes.roll(1) = 0;
    axes.roll_rate(1) = 0;
    axes.roll_a(1) = 0;
    axes.roll_desired(1) = 0;
    axes.pitch(1) = 0;
    axes.pitch_rate(1) = 0;
    axes.pitch_a(1) = 0;
    axes.pitch_desired(1) = 0;
    axes.yaw(1) = atan2d(v.E(1), v.N(1));
    axes.yaw_rate(1) = 0;
    axes.yaw_a(1) = 0;
    axes.yaw_desired(1) = 0;
    
    forces = struct('W', zeros(1,steps), ...
        'L', zeros(1,steps), ...
        'D', zeros(1,steps), ...
        'T', zeros(1,steps));
    
    forces.W(1) = 2.3; %N
    forces.L(1) = 2.3; %N
    forces.T(1) = 5; %N
    forces.D(1) = 0.2; %N
   
    bounds = struct('w', 150, ... %m
        'h', 400, ...%m
        'x_ll', -75, ... %X coord of lower left corner
        'y0_ll', -200, ...
        'boundary_padding', 10, ...
        'aircraft_padding', 50, ...
        'max_r', 10, ...
        'min_r', 5); %Y coord of lower left corner
    
    %Bundle it all together in one struct 
    vars = struct('a', a, ...
        'v', v, ...
        'pos', pos, ...
        'axes', axes, ...
        'forces', forces,...
        'bounds', bounds, ...
        'targets', targets, ...
        't', zeros(1,steps));
end